---

- name: common tasks prior to provision
  hosts: flask
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - common
    
- name: install and configure nginx
  hosts: flask
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - nginx

- name: install and configure flask
  hosts: flask
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - flask

#- name: Deploys flask app from Github
#  hosts: flask
#  remote_user: ubuntu
#
#  roles:
#    - flaskapp
#
