---

- name: install gunicorn and git
  apt: name={{ item }} state=present
  with_items:
    - gunicorn
    - git

- name: git clone app
  git: repo={{ app_repo }} dest={{ app_directory }} accept_hostkey=true force=yes

- name: start app 
  command: gunicorn {{ app_module }} -D -b localhost:{{ port }} chdir={{ app_directory }}
